import unittest
from pathlib import Path

class DesignUiRegressionTests(unittest.TestCase):
    def test_build_button_is_not_permanently_disabled_and_missing_title_controls_are_safe(self):
        html = (Path(__file__).resolve().parents[1] / 'workbench' / 'design.html').read_text(encoding='utf-8')
        self.assertIn('function syncBuildEnabled()', html)
        self.assertIn("titleMode:titleMode?titleMode.value:'cover-follow'", html)
        self.assertIn('const titleAssetFile=$(\'#titleAssetFile\');', html)
        self.assertIn('if(titleAssetFile){', html)
        self.assertIn("const el=$('#'+id); if(!el)return;", html)
        self.assertIn("syncRail();\n  syncBuildEnabled();\n\n  const fu", html)
        self.assertIn('<button id="btnBuild" class="btn">生成三件套</button>', html)
        self.assertIn('id="fontArtist"', html)
        self.assertIn("artist:fontValue('fontArtist')", html)
        self.assertIn('const CJK_FONT_TARGETS', html)
        self.assertIn('不支持中文', html)
        self.assertIn('@font-face{font-family:"Ma Shan Zheng"', html)
        self.assertIn("['private','个人字体']", html)
        self.assertIn('当前侧封模板文字', html)
        self.assertIn("let SPINE_TEMPLATES={right:'title-artist-classic'", html)
        self.assertIn("editor.insertBefore(template,editor.querySelector('.spineToolbar'))", html)
        self.assertIn('let SPINE_TEMPLATES=', html)
        self.assertIn('id="fontSpineRight"', html)
        self.assertIn('id="spineTextRight"', html)
        self.assertIn('id="spineTextLeft"', html)
        self.assertIn('id="spineTextLeftBack"', html)
        self.assertIn('id="spineTextEditor"', html)
        self.assertIn("function defaultSpineText(){return [$('#album').value.trim(),$('#artist').value.trim()].filter(Boolean).join('｜');}", html)
        self.assertIn("textEditor.value=saved||defaultSpineText();", html)
        self.assertIn("requestAnimationFrame(()=>$('#spineTextEditor').focus())", html)
        self.assertIn('id="spineSizeMm"', html)
        self.assertIn('id="spineBold"', html)
        self.assertIn('id="spineItalic"', html)
        self.assertIn('id="spineCustomColor"', html)
        self.assertIn('data-font-for="fontSpineRight"', html)
        self.assertIn('data-font-for="fontSpineLeft"', html)
        self.assertIn('data-font-for="fontSpineLeftBack"', html)
        self.assertNotIn('id="spineFontSelect"', html)
        self.assertIn('spineAppearance:SPINE_APPEARANCE', html)
        self.assertIn('id=\"formatTooltip\"', html)
        self.assertIn('id="spineColorMenuButton"', html)
        self.assertIn('id="spineColorPopover"', html)
        self.assertIn('id="spineCustomColorButton"', html)
        self.assertIn('id="spineColorMenuButton"', html)
        self.assertIn('id="spineColorPopover"', html)
        self.assertIn('id="spineCustomColorButton"', html)
        self.assertIn('function showFormatTooltip', html)

    def test_ribbon_is_compact_and_switches_between_tool_groups(self):
        html = (Path(__file__).resolve().parents[1] / 'workbench' / 'design.html').read_text(encoding='utf-8')
        self.assertIn('data-ribbon-tab="side"', html)
        self.assertIn('data-ribbon-panel="side"', html)
        self.assertIn('data-ribbon-tab="font"', html)
        self.assertNotIn('<div class="templateFieldTitle">字体 <span>选择后立即套入预览与正式出件</span></div>', html)
        self.assertIn('function setRibbonTab(tab)', html)
        self.assertIn('height:112px', html)
        self.assertIn('grid-template-rows:28px minmax(0,1fr)', html)
        self.assertIn("setRibbonTab('side');", html)

if __name__ == '__main__':
    unittest.main()
